backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "POS System"
        name: "pos-system"
        file: "content/pos-system.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown" }
  - label: "testimonials"
    name: "Testimonials"
    folder: "content/testimonials"
    create: true
    identifier_field: client
    fields:
      - { label: "Client", name: "client", widget: "string" }
      - { label: "Testimonial", name: "testimonial", widget: "text" }
  - label: tests
    name: Tests
    description: "Testimonials in array"
    files:
      - label: "Tests File"
        name: "testsFile"
        file: "content/tests.json"
        allow_add: true
        widget: list
        fields:
          - { label: "Client", name: "client", widget: "string" }
          - { label: "Testimonial", name: "testimonial", widget: "text" }
