import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import Script from "next/script";
import { attributes } from "../content/home.md";

export default function Home() {
  const { title, cats } = attributes;
  console.log(cats);
  return (
    <div className={styles.container}>
      <Script src="https://identity.netlify.com/v1/netlify-identity-widget.js" />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href="/pos-systems">POS Systems</Link>
      <h1>{title}</h1>
      <p>{cats[0].name}</p>
      <p>{cats[0].description}</p>
    </div>
  );
}
