import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import { body, attributes as homeData } from "../content/home.md";
import { attributes as testimonials } from "../content/testimonials.md";

export default function Home() {
  console.log(testimonials);
  console.log(homeData);
  console.log(body);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href="/pos-systems">POS Systems</Link>
      <h1></h1>

      <p></p>
    </div>
  );
}
