import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import { attributes } from "../content/pos-system.md";

export default function POS() {
  console.log(attributes);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href="/">Home</Link>
      <h1>POS Systems</h1>
    </div>
  );
}
