import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import { attributes, react as POSContent } from "../content/pos-system.md";

export default function POS() {
  const { title } = attributes;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <span style={{ paddingRight: "20px" }}>
        <Link href="/">Home</Link>{" "}
      </span>
      <Link href="/pos-systems">POS Systems</Link>
      <h1>{title}</h1>

      <POSContent />
    </div>
  );
}
